### ISSUE TITLE
Difference between github fetch and o-bridge-github?

### ISSUE THREAD

**Issue by samuelandert** [hackers4peace/o-bridge-github#1]
What is the difference between the two repos?

**Comment by elf-pavlik** [comment]
o-bridge-github uses github-fetch

another project may also need very simple wrapper like github-fetch but no all the service functionality from o-bridge-github

i also already had most of github-fetch code in a repo with previous experiment, if i find existing javascript github client which provides same functionality, i can just switch that dependency.
